# Generated by Django 3.0.2 on 2020-01-28 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniGithub', '0005_project_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
