# Generated by Django 3.0.2 on 2020-01-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0006_auto_20200128_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='milestone',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='linked_milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniGithub.Milestone'),
        ),
    ]
