# Generated by Django 3.0.2 on 2020-02-05 18:20

from django.db import migrations, models
import django.db.models.deletion
import miniGithub.models


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0008_change_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_State',
            fields=[
                ('custom_event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='miniGithub.Custom_Event')),
                ('current_state', models.CharField(choices=[(miniGithub.models.Problem_State['OPEN'], 1), (miniGithub.models.Problem_State['CLOSED'], 2)], max_length=2)),
            ],
            bases=('miniGithub.custom_event',),
        ),
    ]
