# Generated by Django 3.0.2 on 2020-02-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0009_change_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Milestone',
            fields=[
                ('custom_event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='miniGithub.Custom_Event')),
                ('current_milestone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniGithub.Milestone')),
            ],
            bases=('miniGithub.custom_event',),
        ),
    ]
