# Generated by Django 3.0.2 on 2020-02-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0010_change_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_url', models.CharField(max_length=100)),
                ('commit_id', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('creator', models.CharField(max_length=100)),
                ('creator_email', models.CharField(max_length=100)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniGithub.Problem')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniGithub.Project')),
            ],
        ),
    ]
