# Generated by Django 3.0.2 on 2020-02-22 23:05

from django.db import migrations, models
import miniGithub.models


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0013_problem_current_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_milestone',
            name='current_state',
            field=models.CharField(choices=[(miniGithub.models.Problem_State['OPEN'], 1), (miniGithub.models.Problem_State['CLOSED'], 2)], max_length=2, null=True),
        ),
    ]
