# Generated by Django 3.0.2 on 2020-02-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0014_auto_20200217_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change_Label',
            fields=[
                ('custom_event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='miniGithub.Custom_Event')),
                ('is_linking_event', models.BooleanField()),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miniGithub.Label')),
            ],
            bases=('miniGithub.custom_event',),
        ),
    ]
