# Generated by Django 3.0.2 on 2020-02-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniGithub', '0015_auto_20200222_2323'),
        ('miniGithub', '0015_change_label'),
    ]

    operations = [
    ]
